class Hour {
  double tempc;
  double tempf;
  double windmph;
  double windkph;
  double pressuremb;
  double pressurein;
  double precipmm;
  double precipin;
  double viskm;
  double vismiles;
  double gustmph;
  double gustkph;
  double uv;
  double feelslikec;
  double feelslikef;
  double windchillc;
  double windchillf;
  double heatindexc;
  double heatindexf;
  double dewpointc;
  double dewpointf;
  int winddegree;
  int isday;
  int timeepoch;
  int humidity;
  int cloud;
  int willitrain;
  int chanceofrain;
  int willitsnow;
  int chanceofsnow;
  String time;
  String winddir;
  String text;
  String icon;

  Hour({
    required this.chanceofrain,
    required this.chanceofsnow,
    required this.cloud,
    required this.dewpointc,
    required this.dewpointf,
    required this.feelslikec,
    required this.feelslikef,
    required this.gustkph,
    required this.gustmph,
    required this.heatindexc,
    required this.heatindexf,
    required this.humidity,
    required this.isday,
    required this.precipin,
    required this.precipmm,
    required this.pressurein,
    required this.pressuremb,
    required this.tempf,
    required this.tempc,
    required this.time,
    required this.timeepoch,
    required this.uv,
    required this.viskm,
    required this.vismiles,
    required this.willitrain,
    required this.willitsnow,
    required this.windchillc,
    required this.windchillf,
    required this.winddegree,
    required this.winddir,
    required this.windkph,
    required this.windmph,
    required this.text,
    required this.icon,
  });

  factory Hour.fromMap(Map<String, dynamic> map) {
    Hour hour;
    hour = Hour(
      timeepoch: map['time_epoch'],
      time: map['time'].toString().substring(11),
      tempc: map['temp_c'],
      tempf: map['temp_f'],
      isday: map['is_day'],
      windmph: map['wind_mph'],
      windkph: map['wind_kph'],
      winddegree: map['wind_degree'],
      winddir: map['wind_dir'],
      pressuremb: map['pressure_mb'],
      pressurein: map['pressure_in'],
      precipmm: map['precip_mm'],
      precipin: map['precip_in'],
      humidity: map['humidity'],
      cloud: map['cloud'],
      feelslikec: map['feelslike_c'],
      feelslikef: map['feelslike_f'],
      windchillc: map['windchill_c'],
      windchillf: map['windchill_f'],
      heatindexc: map['heatindex_c'],
      heatindexf: map['heatindex_f'],
      dewpointc: map['dewpoint_c'],
      dewpointf: map['dewpoint_f'],
      willitrain: map['will_it_rain'],
      willitsnow: map['will_it_snow'],
      chanceofrain: map['chance_of_rain'],
      chanceofsnow: map['chance_of_snow'],
      viskm: map['vis_km'],
      vismiles: map['vis_miles'],
      gustmph: map['gust_mph'],
      gustkph: map['gust_kph'],
      uv: map['uv'],
      text: map['condition']['text'],
      icon: map['condition']['icon'],
    );
    return hour;
  }
}
